### ISSUE TITLE
Add permissions for global objects/APIs

### ISSUE THREAD

**Issue by rekmarks** [MetaMask/metamask-snaps-beta#38]
As noted in #30 and elsewhere, a plugin should have to request the globals it needs by means of permissions.

We need to check this permission and dynamically select the requested globals before the plugin code is evaluated by SES.

**Comment by danfinlay** [comment]
Depending how tightly we want to be auditing our first MVP plugins, allowing at least the attenuation of network access (provide a minimal network-enabling proxy when a certain permission is granted) to the site.

We need to extend the permissions-controller so that its rpc-cap permissions schema can also receive and enforce limitations on local APIs, so we can restrict browser APIs to plugins (like ensuring fetch or websockets can only access certain sites). Can also be used later for enforcing permissions over a capnode or captp API to sites.

**Comment by danfinlay** [comment]
Opened a discussion for making some common API proxies here: https://ocapjs.org/t/published-attenuating-proxies-for-common-web-apis/123

**Comment by danfinlay** [comment]
In that discussion, MarkM recommends using this membrane library, and writing "distortion definitions" for it:
https://github.com/caridy/secure-javascript-environment

**Comment by rekmarks** [comment]
The new `PermissionController` has a feature that enables this.
